optimizer:

  type: "SGD"
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0001

model:
  name: "TEST"

training:
  epochs: 50
  batch_size: 32
  shuffle: true
  num_workers: 4
  seed: 42

transforms:
  - type: "FFT"
  - type: "bands"