[project]
name = "spa"
version = "0.1.0"
description = "Sleep Pattern Analysis"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch",
    "torchvision",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "plotly>=5.22.0",
    "pyedflib>=0.1.42",
    "scipy",
    "pyyaml>=6.0.2",
    "pydantic>=2.11.7",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
    { index = "pytorch-cpu", marker = "sys_platform != 'linux' and sys_platform != 'win32'" }
]
torchvision = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
    { index = "pytorch-cpu", marker = "sys_platform != 'linux' and sys_platform != 'win32'" }
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
