trainer:
  epochs: 150
  learning_rate: 0.001
  optimizer: adam
  grad_clip: null
  validate_per_epoch: 50
  early_stopping:
    enabled: false
    patience: 100
    min_delta: 0.001
  scheduler:
    enabled: true
    type: exponential
    step_size: null
    gamma: 0.99993
validator:
  nmi: true
  accuracy: true
  cross_nmi: true
  learning_rate: true
  state_distinctness: true
  summary_statistics: true
  log_likelihood: true
visualizer:
  losses: true
  learning_rate: true
  pca_tripanel: true
  confusion_matrix: true
  state_distinctness: true
  summary_statistics: true
  historic_values: true
dataloader:
  num_batches: 150
  batch_size: 120
  validation_batch_size: 4096
  window_size: null
  sequence_length: 1
  stride: null
  transforms:
  - type: percentile_clipping
    channel: EEG
    params:
      percentile: 0.5
  - type: percentile_clipping
    channel: EMG
    params:
      percentile: 0.1
  shuffle: true
  normalize: true
  use_legacy: true
model:
  type: hmm
  covariance_type: full
  init_strategy: random_uniform
  init_noisy: true
  features: false
  conditioning_source: subject
  n_states: 3
  params: {}
verbose: true
seed: 123
runs: 1
validate_data: true
wandb:
  enabled: true
  group: null
  tags: null
cvae:
  feature_pipeline: fft
  normalize_global: false
  pre_normalize: false
  post_normalize: false
  percentile_clip_channels: false
  perform_hanning_window: false
  band_pass_filter_fft: false
  band_pass_freqs: null
  band_pass_filter_type: frequency_domain
  traning_pipeline: marhmm
  model_checkpoint_path: null
  reinit_marhmm: false
num_states: null
train_datasets:
- type: mssv
  id: sub-071
  run: 1
  remove_artifact: true
  signals:
  - EEG1
  - EEG4
  - EMG
- type: mssv
  id: sub-071
  run: 2
  remove_artifact: true
  signals:
  - EEG1
  - EEG4
  - EMG
- type: mssv
  id: sub-077
  run: 1
  remove_artifact: true
  signals:
  - EEG1
  - EEG4
  - EMG
- type: mssv
  id: sub-077
  run: 2
  remove_artifact: true
  signals:
  - EEG1
  - EEG4
  - EMG
- type: mssv
  id: sub-080
  run: 1
  remove_artifact: true
  signals:
  - EEG1
  - EEG4
  - EMG
- type: mssv
  id: sub-080
  run: 2
  remove_artifact: true
  signals:
  - EEG1
  - EEG4
  - EMG
- type: mssv
  id: sub-081
  run: 1
  remove_artifact: true
  signals:
  - EEG1
  - EEG4
  - EMG
- type: mssv
  id: sub-081
  run: 2
  remove_artifact: true
  signals:
  - EEG1
  - EEG4
  - EMG
val_datasets:
- type: mssv
  id: sub-072
  run: 1
  remove_artifact: true
  signals:
  - EEG1
  - EEG4
  - EMG
- type: mssv
  id: sub-072
  run: 2
  remove_artifact: true
  signals:
  - EEG1
  - EEG4
  - EMG
- type: mssv
  id: sub-076
  run: 1
  remove_artifact: true
  signals:
  - EEG1
  - EEG4
  - EMG
- type: mssv
  id: sub-076
  run: 2
  remove_artifact: true
  signals:
  - EEG1
  - EEG4
  - EMG
results_dir: results/cv4fold/hmm_raw/unified_holdout/lab_2/fold_2
run_name: cv4fold_hmm_raw_within_lab_2_fold2
