trainer:
  epochs: 50
  learning_rate: 0.0003
  optimizer: adam
  grad_clip: 0.5
  validate_per_epoch: 1
  early_stopping:
    enabled: false
    patience: 100
    min_delta: 0.001
  scheduler:
    enabled: false
    type: exponential
    step_size: Null
    gamma: 0.99
validator:
  nmi: True
  accuracy: True
  cross_nmi: True
  learning_rate: True
  state_distinctness: True
  summary_statistics: True
  log_likelihood: True
visualizer:
  losses: True
  learning_rate: True
  pca_tripanel: True
  confusion_matrix: True
  state_distinctness: True
  summary_statistics: True
  historic_values: True
dataloader:
  num_batches: 64
  batch_size: 128
  validation_batch_size: 128
  window_size: 512
  stride: 512
  sequence_length: 1
  shuffle: True
  normalize: True
  use_legacy: False
  transforms: []

train_datasets:
  - type: mssv
    id: sub-038
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-038
    run: 2
    remove_artifact: True
  - type: mssv
    id: sub-039
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-039
    run: 2
    remove_artifact: True
  - type: mssv
    id: sub-039
    run: 3
    remove_artifact: True
  - type: mssv
    id: sub-041
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-041
    run: 2
    remove_artifact: True
  - type: mssv
    id: sub-041
    run: 3
    remove_artifact: True
  - type: mssv
    id: sub-043
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-048
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-048
    run: 2
    remove_artifact: True
  - type: mssv
    id: sub-048
    run: 3
    remove_artifact: True
  - type: mssv
    id: sub-054
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-054
    run: 2
    remove_artifact: True
  - type: mssv
    id: sub-056
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-059
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-060
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-069
    run: 1
    remove_artifact: True

val_datasets:
  - type: mssv
    id: sub-038
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-038
    run: 2
    remove_artifact: True
  - type: mssv
    id: sub-039
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-039
    run: 2
    remove_artifact: True
  - type: mssv
    id: sub-039
    run: 3
    remove_artifact: True
  - type: mssv
    id: sub-041
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-041
    run: 2
    remove_artifact: True
  - type: mssv
    id: sub-041
    run: 3
    remove_artifact: True
  - type: mssv
    id: sub-043
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-048
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-048
    run: 2
    remove_artifact: True
  - type: mssv
    id: sub-048
    run: 3
    remove_artifact: True
  - type: mssv
    id: sub-054
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-054
    run: 2
    remove_artifact: True
  - type: mssv
    id: sub-056
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-059
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-060
    run: 1
    remove_artifact: True
  - type: mssv
    id: sub-069
    run: 1
    remove_artifact: True

model:
  type: cvae_marhmm
  covariance_type: full
  init_strategy: random_uniform
  init_noisy: true
  features: false
  params:
    
    # MARHMM parameters
    lags: [1, 2, 3]
    ridge: 2.0 # FIXED
    var_reg: 1.0 # FIXED
    sticky_coef: 1e-2 # FIXED
    sticky_kappa: 0.8 # EXPERIMENTAL
    
    # CVAE parameters
    # weights
    latent_dim: 8
    enc_hidden_dims: [256, 128]
    dec_hidden_dims: [128, 256]
    conv_channels: [32, 64, 128, 128]
    kernel_sizes:  [7, 5, 5, 3]
    strides:       [2, 2, 2, 2]
    paddings:      [3, 2, 2, 1]
    emb_dim: 4
    use_rms: False
    # prior
    prior: gmm
    min_beta: 0.01
    max_beta: 1.0
    beta_warmup_epochs: 0
    beta_slowdown_epochs: 0
    gmm_warmup_epochs: 0
    free_nats_per_dim: 0.00
    no_beta_epochs: 10
    num_gmm_states: 7

cvae:
  normalize_global: False # FIXED
  pre_normalize: False # FIXED
  post_normalize: True # FIXED
  percentile_clip_channels: False # FIXED
  perform_hanning_window: False # FIXED
  band_pass_filter_fft: True # FIXED
  band_pass_freqs: [[null, 20.0], [null, 20.0], [5.0, 60.0]] # FIXED
  band_pass_filter_type: frequency_domain # FIXED
  traning_pipeline: cvae
  model_checkpoint_path: null
  reinit_marhmm: False

verbose: True
seed: 123
results_dir: results/substages/cvae
run_name: substages_vae_7
runs: 1
validate_data: True
num_states: 7