method: grid
metric:
  name: train/total_loss
  goal: minimize
parameters:
  trainer.learning_rate:
    values: [0.0005, 0.0001, 0.00005]
  model.init_strategy:
    values: [random_uniform, random_separated, kmeans_pca_noisy]
base_config: src/config/run/marhmm/experiments/experiment_mssv_raw.yaml
