method: bayes
metric:
  name: val/nmi
  goal: maximize
parameters:
  trainer.learning_rate:
    distribution: log_uniform
    min: 1e-5
    max: 5e-3
  model.covariance_type:
    values: [full, diag]
early_terminate:
  type: hyperband
  min_iter: 3
base_config: src/config/run/hmm/config_random_uniform.yaml
count: 24
