trainer:
  epochs: 80
  learning_rate: 0.0003
  optimizer: adam
  grad_clip: 0.5
  validate_per_epoch: 1
  early_stopping:
    enabled: false
    patience: 100
    min_delta: 0.001
  scheduler:
    enabled: false
    type: exponential
    step_size: Null
    gamma: 0.99
validator:
  nmi: True
  accuracy: True
  cross_nmi: False
  learning_rate: True
  state_distinctness: True
  summary_statistics: True
  log_likelihood: True
visualizer:
  losses: True
  learning_rate: True
  pca_tripanel: True
  confusion_matrix: True
  state_distinctness: True
  summary_statistics: True
  historic_values: True
dataloader:
  num_batches: 64
  batch_size: 128
  validation_batch_size: 128
  window_size: 512
  stride: 512
  sequence_length: 1
  shuffle: True
  normalize: True
  use_legacy: False
  transforms: []

train_datasets:
  - type: mssv
    lab: lab_2
    remove_artifact: True
    signals:
      - EEG1
      - EEG3
      - EMG
    quality_filter:
      - sub-071
      - sub-072
      - sub-076
      - sub-077
      - sub-080
      - sub-081
  - type: mssv
    lab: lab_3
    remove_artifact: True
    signals:
      - EEG1
      - EEG2
      - EMG
    quality_filter:
      - sub-038
      - sub-039
      - sub-041
      - sub-043
      - sub-048
      - sub-054
      - sub-056
      - sub-059
      - sub-060
      - sub-069

val_datasets:
  - type: mssv
    lab: lab_5
    remove_artifact: True
    signals:
      - EEG1
      - EEG2
      - EMG
    quality_filter:
      - sub-087
      - sub-088
      - sub-089
      - sub-092

model:
  type: cvae_marhmm
  covariance_type: full
  init_strategy: random_uniform
  init_noisy: true
  features: false
  conditioning_source: subject
  params:
    lags: [1, 2, 4]
    ridge: 0.1
    var_reg: 0.05
    sticky_coef: 0.1
    sticky_kappa: 0.9
    latent_dim: 8
    enc_hidden_dims: [256, 128]
    dec_hidden_dims: [128, 256]
    conv_channels: [32, 64, 128, 128]
    kernel_sizes: [7, 5, 5, 3]
    strides: [2, 2, 2, 2]
    paddings: [3, 2, 2, 1]
    emb_dim: 4
    decoder_only_conditioning: true
    use_rms: False
    prior: gmm
    min_beta: 0.01
    max_beta: 1.0
    beta_warmup_epochs: 0
    beta_slowdown_epochs: 0
    gmm_warmup_epochs: 0
    free_nats_per_dim: 0.00
    no_beta_epochs: 10

cvae:
  normalize_global: False
  pre_normalize: False
  post_normalize: True
  percentile_clip_channels: False
  perform_hanning_window: False
  band_pass_filter_fft: True
  band_pass_freqs: [[null, 20.0], [null, 20.0], [5.0, 60.0]]
  band_pass_filter_type: frequency_domain
  training_pipeline: cvae
  model_checkpoint_path: results/lab_conditioning/subject_conditioning_not_lab_LOLO/holdout_lab5/cvae_final_model.pth
  reinit_marhmm: false

verbose: True
seed: 123
results_dir: results/lab_conditioning/subject_conditioning_not_lab_LOLO/holdout_lab5
run_name: generalization_subject_only_holdout_lab5
runs: 3
validate_data: True
