#!/usr/bin/env python3
"""Fold-4 A/B/C table for decoder-only cgmvae roadmap (seq1 vs seq64 vs subject_lab)."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import pandas as pd

from scripts.cv4fold.aggregate_val_nmi_by_lab import _val_mouse_ids
from scripts.cv4fold.select_best_vae_run import parse_nmi
from scripts.cv4fold.summarize_subject_lab_cv import LABS, _latest_timestamp_dir, _macro_mice_nmi

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = REPO_ROOT / "results/cv4fold/decoder_only_fold4"

STEPS = (
    ("A", "subject_tune_winners_seq1", "seq1 + subject"),
    ("B", "subject_tune_winners", "seq64 + subject"),
    ("C", "subject_lab_tune_winners", "seq64 + subject_lab"),
)
FOLD = 4


def _fold_result_root(experiment: str) -> Path:
    return REPO_ROOT / "results/cv4fold" / experiment / "cgmvae" / "joint" / f"fold_{FOLD}"


def _best_run_row(
    result_root: Path, step: str, label: str, experiment: str
) -> dict | None:
    cfg_path = result_root / "config.json"
    if not cfg_path.exists():
        return None
    cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
    val_ids = _val_mouse_ids(cfg)
    by_lab_path = result_root / "val_nmi_by_lab.csv"
    if not by_lab_path.exists():
        return None
    df = pd.read_csv(by_lab_path)
    best_nmi = -1.0
    best_run = None
    row_out: dict | None = None
    for run_num in (1, 2, 3):
        nmi = parse_nmi(result_root / str(run_num) / "plots" / "metrics.txt")
        if nmi is None:
            continue
        if nmi > best_nmi:
            best_nmi = nmi
            best_run = run_num
            sub = df[df["run"] == run_num]
            row_out = {
                "step": step,
                "label": label,
                "experiment": experiment,
                "best_run": run_num,
                "nmi_pooled": nmi,
                "nmi_macro_mice": _macro_mice_nmi(result_root, run_num, val_ids),
                "result_dir": str(result_root),
            }
            for lab in LABS:
                lab_sub = sub[sub["lab"] == lab]
                row_out[f"nmi_{lab}"] = (
                    float(lab_sub["nmi_macro"].iloc[0]) if len(lab_sub) else None
                )
    return row_out


def collect_comparison(postprocess: bool) -> pd.DataFrame:
    rows: list[dict] = []
    for step, experiment, label in STEPS:
        fold_dir = _fold_result_root(experiment)
        latest = _latest_timestamp_dir(fold_dir)
        if latest is None:
            rows.append(
                {
                    "step": step,
                    "label": label,
                    "experiment": experiment,
                    "status": "missing",
                }
            )
            continue
        if postprocess:
            subprocess.run(
                [
                    sys.executable,
                    str(REPO_ROOT / "scripts/cv4fold/postprocess_fold.py"),
                    "--result-root",
                    str(latest),
                ],
                check=False,
                cwd=REPO_ROOT,
            )
        row = _best_run_row(latest, step, label, experiment)
        if row is None:
            rows.append(
                {
                    "step": step,
                    "label": label,
                    "experiment": experiment,
                    "status": "no_metrics",
                    "result_dir": str(latest),
                }
            )
        else:
            row["status"] = "ok"
            rows.append(row)
    return pd.DataFrame(rows)


def _write_markdown(df: pd.DataFrame, path: Path) -> None:
    lines = [
        "# Decoder-only fold 4 comparison",
        "",
        "Auto-generated by `scripts/cv4fold/summarize_decoder_only_fold4.py`.",
        "",
    ]
    if df.empty:
        lines.append("_No rows._")
    else:
        cols = [
            c
            for c in [
                "step",
                "label",
                "nmi_pooled",
                "nmi_lab_2",
                "nmi_lab_3",
                "nmi_lab_5",
                "nmi_macro_mice",
                "best_run",
                "status",
            ]
            if c in df.columns
        ]
        lines.append("| " + " | ".join(cols) + " |")
        lines.append("| " + " | ".join("---" for _ in cols) + " |")
        for _, r in df.iterrows():
            cells = [str(r.get(c, "")) for c in cols]
            lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--postprocess",
        action="store_true",
        help="Run postprocess_fold.py on each latest result before summarizing",
    )
    args = parser.parse_args()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    df = collect_comparison(postprocess=args.postprocess)
    csv_path = OUT_DIR / "comparison.csv"
    md_path = OUT_DIR / "comparison.md"
    df.to_csv(csv_path, index=False)
    _write_markdown(df, md_path)
    print(f"Wrote {csv_path}")
    print(f"Wrote {md_path}")
    if (df.get("status") == "ok").any() if "status" in df.columns else False:
        print(df.to_string(index=False))
    else:
        print("No completed runs yet — re-run after jobs finish.")


if __name__ == "__main__":
    main()
