trainer:
  epochs: 20
  learning_rate: 0.001
validator:
  nmi: True
visualizer:
  losses: True
dataloader:
  batch_size: 1024
  shuffle: True
  transforms:
    - type: reshape
      params: {}
dataset:
  type: mssv
  id: sub-001
model:
  type: hmm
verbose: true
seed: 123
results_dir: results/training
run_name: no_features