trainer:
  epochs: 50
  learning_rate: 0.001
validator:
  nmi: True
visualizer:
  losses: True
  pca_tripanel: True
  pca_top_k: 4
dataloader:
  batch_size: 5120
  shuffle: True
  transforms:
    - type: reshape
      params: {}
    - type: fft
      params: {
        "window_size": 512,
      }
dataset:
  type: synthetic
  id: test
model:
  type: hmm
  init_strategy: kmeans_noisy
verbose: true
seed: 123
results_dir: results/training
run_name: test