trainer:
  epochs: 100
  learning_rate: 0.001
validator:
  nmi: True
visualizer:
  losses: True
dataloader:
  batch_size: 5120
  shuffle: True
  transforms:
    - type: fft
      params: {
        "window_size": 512,
      }
    - type: collapse_dimensions
      params: {}
dataset:
  type: synthetic
  id: test
model:
  type: hmm
verbose: true
seed: 123
results_dir: results/training
run_name: test