trainer:
  epochs: 100
  learning_rate: 0.001
  optimizer: adam
validator:
  nmi: True
  cross_nmi: True
  state_distinctness: True
visualizer:
  losses: True
  pca_tripanel: True
  confusion_matrix: True
  pca_top_k: 4
  state_distinctness: True
  pairwise_energy_distance: True
  fisher: True
dataloader:
  batch_size: 16384
  shuffle: True
  normalize: True
  transforms:
    - type: reshape
      params: {}
    - type: fft
      params: {
        "window_size": 512,
        "feature": "power",
      }
dataset:
  type: synthetic
  id: test
model:
  type: hmm
  init_strategy: kmeans
verbose: true
seed: 123
results_dir: results/training
run_name: feature_synthetic
runs: 5
