trainer:
  epochs: 700
  learning_rate: 0.0005
  optimizer: adam
validator:
  nmi: True
  cross_nmi: True
  state_distinctness: True
visualizer:
  losses: True
  pca_tripanel: True
  confusion_matrix: True
  state_distinctness: True
dataloader:
  batch_size: 16384
  shuffle: True
  normalize: True
  transforms:
    - type: reshape
      params: {}
    - type: fft
      params: {
        "window_size": 512,
        "feature": "power",
      }
dataset:
  type: synthetic
  id: test3
model:
  type: hmm
  init_strategy: random_separated
verbose: true
seed: 123
results_dir: results/training
run_name: feature_synthetic_separated
runs: 5