trainer:
  epochs: 1
  learning_rate: 0.05
validator:
  nmi: True
visualizer:
  losses: True
dataloader:
  batch_size: 5120
  shuffle: True
  transforms:
    - type: reshape
      params: {}
    - type: fft
      params: {
        "window_size": 512,
      }
dataset:
  type: mssv
  id: sub-001
model:
  type: hmm
  init_strategy: kmeans
verbose: true
seed: 123
results_dir: results/training
run_name: real