trainer:
  epochs: 10
  learning_rate: 0.001
validator:
  nmi: True
visualizer:
  losses: True
dataloader:
  batch_size: 5120
  transforms:
    - type: fft
      params: {
        "window_size": 512,
      }
    - type: collapse_dimensions
      params: {}
dataset:
  type: mssv
  id: sub-001
model:
  type: hmm
verbose: true
results_dir: results/training
run_name: real