trainer:
  epochs: 700
  learning_rate: 0.0005
  optimizer: adam
validator:
  nmi: True
  cross_nmi: True
  state_distinctness: True
visualizer:
  losses: True
  pca_tripanel: True
  confusion_matrix: True
  state_distinctness: True
dataloader:
  batch_size: 16384
  shuffle: True
  normalize: True
  transforms:
    - type: reshape
      params: {}
    - type: fft
      params: {
        "window_size": 512,
        "feature": "power",
      }
dataset:
  type: synthetic
  id: test3
model:
  type: marhmm
  init_strategy: random_dirichlet
  init_noisy: false
  params:
    lags: [1, 2, 4, 8]
    normalize_time: false
    ridge: 0.01
    ignore_prefix: true
    drop_prefix_from_normalization: true
verbose: true
seed: 123
results_dir: results/training
run_name: feature_synthetic_marhmm_dirichlet
runs: 5
