#!/usr/bin/env python3
"""Build curated paper figure set → docs/paper/figures/curated/ (+ copy to docs/paper/figures/)."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CURATED = REPO / "docs/paper/figures/curated"
PAPER_FIGS = REPO / "docs/paper/figures"
PAPER_MAIN = PAPER_FIGS / "main"
PAPER_SI = PAPER_FIGS / "supplementary"
NPZ_K4 = (
    REPO
    / "results/cv4fold/paper_k_sweep/fold_4/K4/joint_k_sweep_f4_K4_20260609-183717/plots/3/results.npz"
)
NPZ_HOLDOUT = (
    REPO
    / "results/cv4fold/joint_holdout/fold_4/chmmgmvae_locked"
    / "joint_ho_f4_chmmgmvae_locked_20260610-040158/plots/1/results.npz"
)


def _run(cmd: list[str]) -> None:
    print("+", " ".join(cmd))
    subprocess.run(cmd, check=True, cwd=REPO)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--npz-k4", type=Path, default=NPZ_K4)
    parser.add_argument("--npz-holdout", type=Path, default=NPZ_HOLDOUT)
    parser.add_argument("--skip-summarize", action="store_true")
    args = parser.parse_args()

    CURATED.mkdir(parents=True, exist_ok=True)
    py = sys.executable

    if not args.skip_summarize:
        _run([py, "scripts/paper/summarize_holdout_ladder.py"])
        _run([py, "scripts/paper/scrape_holdout_accuracy.py"])

    figures: dict[str, str] = {}

    def fig(name: str, script_args: list[str]) -> None:
        out = CURATED / name
        _run([py] + script_args + ["--out", str(out)])
        figures[name] = str(out)

    _run([py, "scripts/paper/plot_fig1_schematic.py", "--out", str(CURATED / "Fig1_protocol.pdf")])
    figures["Fig1_protocol.pdf"] = str(CURATED / "Fig1_protocol.pdf")

    fig("Fig2_holdout_ladder.pdf", ["scripts/paper/plot_ladder_figure.py"])
    fig("Fig3_lab_heterogeneity.pdf", ["scripts/paper/plot_within_lab_heatmap.py"])
    fig("S2_k_sweep.pdf", ["scripts/paper/plot_k_sweep_dual_axis.py"])
    fig("S1_ladder_complete.pdf", ["scripts/paper/plot_ladder_figure.py", "--by-fold"])

    if args.npz_k4.is_file():
        fig("Fig4_substage_biology.pdf", ["scripts/paper/plot_fig4_substage_compact.py", "--npz", str(args.npz_k4)])
        _run([
            py, "scripts/paper/plot_figure27_compact.py",
            "--npz", str(args.npz_k4),
            "--out-fig4", str(CURATED / "Fig5_dynamics.pdf"),
            "--out-panel", str(CURATED / "Fig3_substage_panels_full.pdf"),
        ])
        figures["Fig5_dynamics.pdf"] = str(CURATED / "Fig5_dynamics.pdf")
    else:
        print(f"Skip substage figures: missing {args.npz_k4}")

    if args.npz_holdout.is_file():
        fig("S3_confusion_exemplar.pdf", ["scripts/paper/plot_confusion_matrix.py", "--npz", str(args.npz_holdout)])
    fig("S4_per_mouse_nmi.pdf", ["scripts/paper/plot_per_mouse_nmi.py"])

    # Copy to docs/paper/figures/{main,supplementary,archive}
    main_mapping = {
        "Fig1_protocol.pdf": "Fig1.pdf",
        "Fig5_dynamics.pdf": "Fig5.pdf",
        "S2_k_sweep.pdf": "S3_k_sweep.pdf",
    }
    si_mapping = {
        "S1_ladder_complete.pdf": "S1_ladder_by_fold.pdf",
        "S3_confusion_exemplar.pdf": "S3_confusion.pdf",
        "S4_per_mouse_nmi.pdf": "S4_per_mouse_nmi.pdf",
        "Fig3_substage_panels_full.pdf": "Fig3_substage_panels_full.pdf",
    }
    archive_mapping = {
        "Fig2_holdout_ladder.pdf": "Fig2.pdf",
        "Fig3_lab_heterogeneity.pdf": "Fig3.pdf",
        "Fig4_substage_biology.pdf": "Fig4.pdf",
    }
    PAPER_MAIN.mkdir(parents=True, exist_ok=True)
    PAPER_SI.mkdir(parents=True, exist_ok=True)
    (PAPER_FIGS / "archive").mkdir(parents=True, exist_ok=True)

    def _copy_set(mapping: dict[str, str], dest_dir: Path) -> None:
        for src_name, dst_name in mapping.items():
            src = CURATED / src_name
            if not src.is_file():
                continue
            shutil.copy(src, dest_dir / dst_name)
            tif_src = src.with_suffix(".tif")
            if tif_src.is_file():
                shutil.copy(tif_src, dest_dir / dst_name.replace(".pdf", ".tif"))

    _copy_set(main_mapping, PAPER_MAIN)
    _copy_set(si_mapping, PAPER_SI)
    _copy_set(archive_mapping, PAPER_FIGS / "archive")
    mapping = {**main_mapping, **si_mapping, **archive_mapping}

    manifest = {
        "generated": datetime.now(timezone.utc).isoformat(),
        "figures": figures,
        "upload_mapping": mapping,
        "npz_k4": str(args.npz_k4),
        "npz_holdout": str(args.npz_holdout),
    }
    (CURATED / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    readme = CURATED / "README.md"
    readme.write_text(
        "# Curated paper figures\n\n"
        "Generated by `scripts/paper/build_curated_figures.py`.\n\n"
        "| File | Message | Script |\n"
        "|------|---------|--------|\n"
        "| Fig1_protocol | Cohort + zero-shot protocol + ladder | plot_fig1_schematic.py |\n"
        "| Fig2_holdout_ladder | Joint holdout NMI | plot_ladder_figure.py |\n"
        "| Fig3_lab_heterogeneity | Within-lab model comparison | plot_within_lab_heatmap.py |\n"
        "| Fig4_substage_biology | 2×2 physiology at K=4 | plot_fig4_substage_compact.py |\n"
        "| Fig5_dynamics | Transitions + hypnogram | plot_figure27_compact.py |\n"
        "| S1_ladder_complete | Per-fold bars | plot_ladder_figure.py --by-fold |\n"
        "| S2_k_sweep | K resolution sweep | plot_k_sweep_dual_axis.py |\n"
        "| S3_confusion_exemplar | Macro confusion | plot_confusion_matrix.py |\n"
        "| S4_per_mouse_nmi | Per-mouse fold 4 | plot_per_mouse_nmi.py |\n",
        encoding="utf-8",
    )
    print(f"Wrote {CURATED} ({len(figures)} figures)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
