#!/usr/bin/env python3
"""Build appendix table: holdout prior likelihood at best-of-three seed per fold."""

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
LADDER_CSV = REPO / "paper/overleaf/tables/holdout_ladder.csv"
OUT_TEX = REPO / "docs/paper/assets/tables/S13_holdout_likelihood.tex"
T_SEQ = 64
LATENT_DIM = 6
TL = T_SEQ * LATENT_DIM

MODEL_T = {
    "cgmvae_locked": 1,
    "hmmgmvae_locked": T_SEQ,
    "chmmgmvae_locked": T_SEQ,
}
MODEL_LABEL = {
    "cgmvae_locked": "cGMVAE",
    "hmmgmvae_locked": "HMMGMVAE",
    "chmmgmvae_locked": "cHMM--GMVAE",
}


def _parse_metrics(path: Path) -> dict[str, float]:
    if not path.is_file():
        return {}
    text = path.read_text(encoding="utf-8", errors="replace")
    out: dict[str, float] = {}
    if m := re.search(r"^NMI:\s*([0-9.+-eE]+)", text, re.M):
        out["nmi"] = float(m.group(1))
    if m := re.search(r"^log p\(z_1:T\):\s*([0-9.+-eE]+)", text, re.M):
        out["log_pz"] = float(m.group(1))
    if m := re.search(r"^Likelihood:\s*([0-9.+-eE]+)", text, re.M):
        out["likelihood"] = float(m.group(1))
    return out


def _likelihood_row(model: str, metrics: dict[str, float]) -> tuple[str, str, str]:
    """Return (raw display, normalized display, norm label)."""
    t = MODEL_T.get(model, T_SEQ)
    if model == "cgmvae_locked":
        raw = metrics.get("likelihood")
        if raw is None:
            return "---", "---", "mean $\\log p(z_t)$"
        # T=1: independent epochs; reported value is mean log GMM marginal per epoch.
        norm = raw / LATENT_DIM
        return f"{raw:.2f}", f"{norm:.3f}", f"$/L$, $T{{=}}1$"
    log_pz = metrics.get("log_pz")
    if log_pz is None:
        return "---", "---", f"$/(T\\cdot L)$, $T{{=}}{t}$"
    norm = log_pz / (t * LATENT_DIM)
    return f"{log_pz:.1f}", f"{norm:.3f}", f"$/(T\\cdot L)$, $T{{=}}{t}$"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path, default=LADDER_CSV)
    parser.add_argument("--out", type=Path, default=OUT_TEX)
    args = parser.parse_args()

    rows: list[dict] = []
    with args.csv.open(newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if r["scope"] != "joint" or r["lab"] != "all":
                continue
            if r["model"] not in MODEL_T:
                continue
            root = Path(r["result_root"])
            seed = int(r["selected_run"])
            metrics_path = root / "plots" / str(seed) / "metrics.txt"
            m = _parse_metrics(metrics_path)
            raw, norm, _ = _likelihood_row(r["model"], m)
            rows.append(
                {
                    "fold": r["fold"],
                    "model": r["model"],
                    "label": MODEL_LABEL[r["model"]],
                    "t": MODEL_T[r["model"]],
                    "nmi": m.get("nmi", float("nan")),
                    "raw": raw,
                    "norm": norm,
                    "seed": seed,
                }
            )

    rows.sort(key=lambda x: (int(x["fold"]), ("cgmvae_locked", "hmmgmvae_locked", "chmmgmvae_locked").index(x["model"])))

    lines = [
        "% Auto-generated by scripts/paper/build_holdout_likelihood_table.py",
        "\\begin{tabular}{|l|l|r|r|r|r|}",
        "\\hline",
        "\\textbf{Fold} & \\textbf{Model} & \\textbf{$T$} & \\textbf{Holdout NMI} & "
        "\\textbf{Prior LL (raw)} & \\textbf{Norm.} \\\\",
        "\\thickhline",
    ]
    for row in rows:
        nmi_s = f"{row['nmi']:.3f}" if row["nmi"] == row["nmi"] else "---"
        lines.append(
            f"{row['fold']} & {row['label']} & {row['t']} & {nmi_s} & {row['raw']} & {row['norm']} \\\\"
        )
    lines.extend(["\\hline", "\\end{tabular}"])

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {args.out} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
