#!/usr/bin/env python3
"""Build appendix LaTeX tables for cv4fold cohort inventory and fold splits.

Reads data/manifests/cv_quality_cohort_v1.yaml (single source of truth).
Outputs docs/paper/assets/tables/S8_cv4fold_cohort.tex and S9_cv4fold_splits.tex.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
DEFAULT_MANIFEST = REPO / "data/manifests/cv_quality_cohort_v1.yaml"
OUT_COHORT = REPO / "docs/paper/assets/tables/S8_cv4fold_cohort.tex"
OUT_SPLITS = REPO / "docs/paper/assets/tables/S9_cv4fold_splits.tex"

LAB_LABEL = {"lab_2": "Bern (2)", "lab_3": "Copenhagen (3)", "lab_5": "Lyon (5)"}


def load_data(manifest_path: Path) -> dict:
    return yaml.safe_load(manifest_path.read_text())


def agg_mice(inventory: dict, mice: list[str]) -> tuple[int, int, float, int]:
    n_mice = len(mice)
    n_runs = sum(len(inventory[m]["runs"]) for m in mice)
    hours = sum(float(inventory[m]["hours"]) for m in mice)
    epochs = sum(int(inventory[m]["epochs_4s"]) for m in mice)
    return n_mice, n_runs, hours, epochs


def fmt_hours(h: float) -> str:
    return f"{h:.1f}" if abs(h - round(h)) > 0.05 else f"{int(round(h))}"


def fmt_int(n: int) -> str:
    return f"{n:,}".replace(",", "{,}")


def tex_mouse(sub: str) -> str:
    return sub.replace("_", r"\_")


def build_cohort_table(data: dict) -> str:
    inv = data["inventory"]
    lines = [
        "% Auto-generated by scripts/paper/build_cv4fold_split_tables.py",
        r"\begin{tabular}{|l|l|r|r|r|}",
        r"\hline",
        r"\textbf{Mouse} & \textbf{Site} & \textbf{Runs} & \textbf{Hours} & \textbf{Epochs (4\,s)} \\",
        r"\thickhline",
    ]
    total_runs = total_hours = total_epochs = 0
    for lab_key in ("lab_2", "lab_3", "lab_5"):
        for sub in data["cohort"][lab_key]:
            d = inv[sub]
            nr = len(d["runs"])
            h = float(d["hours"])
            e = int(d["epochs_4s"])
            total_runs += nr
            total_hours += h
            total_epochs += e
            lines.append(
                f"{tex_mouse(sub)} & {LAB_LABEL[lab_key]} & {nr} & {fmt_hours(h)} & {fmt_int(e)} \\\\"
            )
    lines.append(r"\hline")
    lines.append(
        f"\\textbf{{Total (20 mice)}} &  & {total_runs} & {fmt_hours(total_hours)} & {fmt_int(total_epochs)} \\\\"
    )
    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    return "\n".join(lines)


def build_splits_table(data: dict) -> str:
    inv = data["inventory"]
    splits = data["splits"]
    lines = [
        "% Auto-generated by scripts/paper/build_cv4fold_split_tables.py",
        r"\begin{tabular}{|c|l|l|r|r|r|}",
        r"\hline",
        r"\textbf{Fold} & \textbf{Site} & \textbf{Held-out mice} & \textbf{Runs} & \textbf{Hours} & \textbf{Epochs} \\",
        r"\thickhline",
    ]
    for fold in range(1, 5):
        key = f"fold_{fold}"
        for i, lab in enumerate(("lab_2", "lab_3", "lab_5")):
            mice = splits[key].get(lab, [])
            if not mice:
                continue
            nr = sum(len(inv[m]["runs"]) for m in mice)
            h = sum(float(inv[m]["hours"]) for m in mice)
            e = sum(int(inv[m]["epochs_4s"]) for m in mice)
            fold_cell = str(fold) if i == 0 else ""
            mice_str = ", ".join(tex_mouse(m) for m in mice)
            lines.append(
                f"{fold_cell} & {LAB_LABEL[lab]} & {mice_str} & {nr} & {fmt_hours(h)} & {fmt_int(e)} \\\\"
            )
        lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    return "\n".join(lines)


def build_fold_summary_table(data: dict) -> str:
    inv = data["inventory"]
    splits = data["splits"]
    lines = [
        "",
        r"\par\medskip",
        r"\begin{tabular}{|c|r|r|r|r|r|r|r|}",
        r"\hline",
        r"\textbf{Fold} & \textbf{Val mice} & \textbf{Val runs} & \textbf{Val hours} & \textbf{Val epochs} & \textbf{Train mice} & \textbf{Train epochs} & \textbf{Val (\%)} \\",
        r"\thickhline",
    ]
    for fold in range(1, 5):
        key = f"fold_{fold}"
        holdouts: list[str] = []
        for lab in ("lab_2", "lab_3", "lab_5"):
            holdouts.extend(splits[key].get(lab, []))
        train = [m for m in inv if m not in holdouts]
        vn, vr, vh, ve = agg_mice(inv, holdouts)
        tn, tr, th, te = agg_mice(inv, train)
        pct = 100.0 * ve / (ve + te)
        lines.append(
            f"{fold} & {vn} & {vr} & {fmt_hours(vh)} & {fmt_int(ve)} & {tn} & {fmt_int(te)} & {pct:.1f} \\\\"
        )
    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--cohort-out", type=Path, default=OUT_COHORT)
    parser.add_argument("--splits-out", type=Path, default=OUT_SPLITS)
    args = parser.parse_args()

    data = load_data(args.manifest)
    args.cohort_out.parent.mkdir(parents=True, exist_ok=True)
    args.cohort_out.write_text(build_cohort_table(data) + "\n", encoding="utf-8")
    splits_tex = build_splits_table(data) + build_fold_summary_table(data) + "\n"
    args.splits_out.write_text(splits_tex, encoding="utf-8")
    print(f"Wrote {args.cohort_out}")
    print(f"Wrote {args.splits_out}")


if __name__ == "__main__":
    main()
