#!/usr/bin/env python3
"""Compute Cohen kappa, macro-F1, and per-class recall for holdout results.npz."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from scripts.paper.plot_confusion_matrix import _predicted_macro
from src.helpers.align_labels import align_labels_hungarian

REPO = Path(__file__).resolve().parents[2]
MACRO_NAMES = ["Wake", "NREM", "REM"]
DEFAULT_NPZ = (
    REPO
    / "results/cv4fold/joint_holdout/fold_4/chmmgmvae_locked"
    / "joint_ho_f4_chmmgmvae_locked_20260610-040158/plots/1/results.npz"
)


def _cohen_kappa(y_true: np.ndarray, y_pred: np.ndarray, n_classes: int = 3) -> float:
    cm = np.zeros((n_classes, n_classes), dtype=np.float64)
    for t, p in zip(y_true, y_pred, strict=True):
        cm[int(t), int(p)] += 1.0
    n = cm.sum()
    if n == 0:
        return float("nan")
    po = np.trace(cm) / n
    pe = (cm.sum(axis=0) * cm.sum(axis=1)).sum() / (n * n)
    if pe == 1.0:
        return 1.0
    return float((po - pe) / (1.0 - pe))


def _per_class_recall(y_true: np.ndarray, y_pred: np.ndarray, n_classes: int = 3) -> dict[str, float]:
    out: dict[str, float] = {}
    for i, name in enumerate(MACRO_NAMES[:n_classes]):
        mask = y_true == i
        out[name] = float((y_pred[mask] == i).mean()) if mask.any() else float("nan")
    return out


def _macro_f1(y_true: np.ndarray, y_pred: np.ndarray, n_classes: int = 3) -> float:
    f1s: list[float] = []
    for i in range(n_classes):
        tp = int(((y_true == i) & (y_pred == i)).sum())
        fp = int(((y_true != i) & (y_pred == i)).sum())
        fn = int(((y_true == i) & (y_pred != i)).sum())
        if tp == 0 and fp == 0 and fn == 0:
            continue
        prec = tp / (tp + fp) if (tp + fp) else 0.0
        rec = tp / (tp + fn) if (tp + fn) else 0.0
        f1 = 2 * prec * rec / (prec + rec) if (prec + rec) else 0.0
        f1s.append(f1)
    return float(np.mean(f1s)) if f1s else float("nan")


def compute_metrics(npz_path: Path) -> dict:
    data = np.load(npz_path)
    y_true = data["y_true"].reshape(-1)
    y_pred = data["y_hat"].reshape(-1)
    valid = y_true < 3
    y_true = np.clip(y_true[valid].astype(int), 0, 2)
    y_pred = y_pred[valid]
    y_pred_macro = _predicted_macro(y_true, y_pred)

    return {
        "npz": str(npz_path),
        "n_epochs": int(y_true.size),
        "cohen_kappa": _cohen_kappa(y_true, y_pred_macro),
        "macro_f1": _macro_f1(y_true, y_pred_macro),
        "per_class_recall": _per_class_recall(y_true, y_pred_macro),
        "accuracy": float((y_true == y_pred_macro).mean()),
    }


def _write_tex(path: Path, rows: list[dict]) -> None:
    lines = [
        "% Auto-generated by scripts/paper/compute_holdout_classification_metrics.py",
        "\\begin{tabular}{|l|r|r|r|r|r|}",
        "\\hline",
        "\\textbf{Run} & \\textbf{$\\kappa$} & \\textbf{Macro F1} & "
        "\\textbf{Wake rec.} & \\textbf{NREM rec.} & \\textbf{REM rec.} \\\\",
        "\\thickhline",
    ]
    for row in rows:
        rec = row["per_class_recall"]
        lines.append(
            f"{row['label']} & {row['cohen_kappa']:.3f} & {row['macro_f1']:.3f} & "
            f"{rec['Wake']:.3f} & {rec['NREM']:.3f} & {rec['REM']:.3f} \\\\"
        )
    lines.extend(["\\hline", "\\end{tabular}"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--npz", type=Path, action="append", default=None)
    parser.add_argument("--label", type=str, action="append", default=None)
    parser.add_argument(
        "--out-json",
        type=Path,
        default=REPO / "docs/paper/figures/supplementary/S10_per_class_metrics.json",
    )
    parser.add_argument(
        "--out-tex",
        type=Path,
        default=REPO / "docs/paper/assets/tables/S10_per_class_metrics.tex",
    )
    args = parser.parse_args()

    npz_paths = args.npz or [DEFAULT_NPZ]
    labels = args.label or [f"fold4_{i}" for i in range(len(npz_paths))]
    if len(labels) != len(npz_paths):
        raise SystemExit("--label count must match --npz count")

    rows = []
    for label, npz in zip(labels, npz_paths, strict=True):
        m = compute_metrics(npz)
        m["label"] = label
        rows.append(m)
        print(json.dumps(m, indent=2))

    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(rows, indent=2), encoding="utf-8")
    _write_tex(args.out_tex, rows)
    print(f"Wrote {args.out_json}")
    print(f"Wrote {args.out_tex}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
