#!/usr/bin/env python3
"""Seed-level holdout NMI summary (mean ± SD and best-of-3) for paper tables."""

from __future__ import annotations

import argparse
import statistics as stats
from collections import defaultdict
from pathlib import Path

from scripts.cv4fold.select_best_vae_run import collect_run_nmis
from scripts.paper.summarize_holdout_ladder import DEFAULT_ROOTS, MODEL_LABEL

REPO = Path(__file__).resolve().parents[2]
JOINT_MODELS = ("cgmvae_locked", "chmmgmvae_locked")
FOLDS = ("1", "2", "3", "4")


def _latest_run_dir(model_dir: Path) -> Path | None:
    if not model_dir.is_dir():
        return None
    candidates = sorted(
        (p for p in model_dir.iterdir() if p.is_dir()),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    return candidates[0] if candidates else None


def collect_seed_stats() -> list[dict]:
    rows: list[dict] = []
    root = REPO / "results/cv4fold/joint_holdout"
    for fold in FOLDS:
        for model in JOINT_MODELS:
            model_dir = root / f"fold_{fold}" / model
            run_dir = _latest_run_dir(model_dir)
            if run_dir is None:
                continue
            runs = collect_run_nmis(run_dir)
            if not runs:
                continue
            nmis = [n for _, n, _ in runs]
            rows.append(
                {
                    "fold": fold,
                    "model": MODEL_LABEL[model],
                    "n_seeds": len(nmis),
                    "nmi_mean": stats.mean(nmis),
                    "nmi_std": stats.pstdev(nmis) if len(nmis) > 1 else 0.0,
                    "nmi_best": max(nmis),
                    "nmi_min": min(nmis),
                    "per_seed": {str(r): n for r, n, _ in runs},
                }
            )
    return rows


def _write_tex(path: Path, rows: list[dict]) -> None:
    lines = [
        "% Auto-generated by scripts/paper/summarize_holdout_seeds.py",
        "\\begin{tabular}{|l|l|r|r|r|r|}",
        "\\hline",
        "\\textbf{Fold} & \\textbf{Model} & \\textbf{Seeds} & "
        "\\textbf{NMI mean} & \\textbf{NMI SD} & \\textbf{NMI best} \\\\",
        "\\thickhline",
    ]
    for row in rows:
        lines.append(
            f"{row['fold']} & {row['model']} & {row['n_seeds']} & "
            f"{row['nmi_mean']:.3f} & {row['nmi_std']:.3f} & {row['nmi_best']:.3f} \\\\"
        )
    lines.extend(["\\hline", "\\end{tabular}"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out-tex",
        type=Path,
        default=REPO / "docs/paper/assets/tables/S11_seed_stability.tex",
    )
    args = parser.parse_args()

    rows = collect_seed_stats()
    _write_tex(args.out_tex, rows)
    print(f"Wrote {args.out_tex} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
